project:
  type: book

book:
  title: "mta_casinos"
  author: "Don BOyd"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - legislation.qmd
    - timetable.qmd
    - articles.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*

format:
  html:
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt
